---
namespace: "serdigital64"
name: "application"
version: "1.3.2"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating office applications provisioning"
license:
  - "GPL-3.0-or-later"
tags:
  - "application"
  - "productivity"
  - "office"
  - "system"
dependencies:
  serdigital64.system: "*"
  serdigital64.backup: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
