---
version: 2
formats: []
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
python:
  install:
    - requirements: "requirements-mkdocs.txt"
mkdocs:
  configuration: "mkdocs.yml"
  fail_on_warning: false
...
