---
site_name: "A:Platform64 Project"
site_description: "A:Platform64 is an automated infrastructure-as-code management platform based on Ansible."
site_author: "SerDigital64"

site_url: "https://aplatform64.readthedocs.io"
repo_url: "https://github.com/aplatform64/aplatform64"

copyright: "Apache-2.0"
docs_dir: "docs/"
site_dir: "build/site/"
strict: false

extra_css:
  - "css/pygments-tango.css"

plugins:
  - search
  - include-markdown
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true

theme:
  name: readthedocs
  analytics:
    gtag: "G-KMX4RGXREV"
  highlightjs: false
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - toc:
      permalink: true
      baselevel: 2
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.escapeall:
  - pymdownx.tasklist:
  - pymdownx.progressbar:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:
  - pymdownx.inlinehilite:

nav:
  - Home: "index.md"
  - Scripts:
    - ap64: "bin/ap64.md"
  - Contributing:
    - guidelines: "contributing/CONTRIBUTING.md"
    - conduct: "contributing/CODE_OF_CONDUCT.md"
    - license: "contributing/LICENSE"
    - changelog: "contributing/CHANGELOG.md"
  - Playbooks:
    - manage_cloud_control_nodes: "playbooks/manage_cloud_control_nodes.md"
    - manage_dev_nodes: "playbooks/manage_dev_nodes.md"
    - manage_doc_sites: "playbooks/manage_doc_sites.md"
    - manage_file_servers: "playbooks/manage_file_servers.md"
    - manage_git_servers: "playbooks/manage_git_servers.md"
    - manage_gitlab_servers: "playbooks/manage_gitlab_servers.md"
    - manage_hpc_nodes: "playbooks/manage_hpc_nodes.md"
    - manage_jenkins_controllers: "playbooks/manage_jenkins_controllers.md"
    - manage_jenkins_workers: "playbooks/manage_jenkins_workers.md"
    - manage_libvirt_servers: "playbooks/manage_libvirt_servers.md"
    - manage_linux_workstations: "playbooks/manage_linux_workstations.md"
    - manage_linux_servers: "playbooks/manage_linux_servers.md"
    - manage_office_nodes: "playbooks/manage_office_nodes.md"
    - manage_test_nodes: "playbooks/manage_test_nodes.md"
  - Collections:
    - application: "collections/application.md"
    - automation: "collections/automation.md"
    - backup: "collections/backup.md"
    - cloud: "collections/cloud.md"
    - container: "collections/container.md"
    - database: "collections/database.md"
    - development: "collections/development.md"
    - devops: "collections/devops.md"
    - hardware: "collections/hardware.md"
    - hypervisor: "collections/hypervisor.md"
    - infrastructure: "collections/infrastructure.md"
    - monitor: "collections/monitor.md"
    - network: "collections/network.md"
    - security: "collections/security.md"
    - storage: "collections/storage.md"
    - system: "collections/system.md"
    - web: "collections/web.md"
  - Roles:
    - app_blender: "roles/app_blender.md"
    - app_chrome: "roles/app_chrome.md"
    - app_darktable: "roles/app_darktable.md"
    - app_drawio: "roles/app_drawio.md"
    - app_firefox: "roles/app_firefox.md"
    - app_freecad: "roles/app_freecad.md"
    - app_gimp: "roles/app_gimp.md"
    - app_inkscape: "roles/app_inkscape.md"
    - app_keepassxc: "roles/app_keepassxc.md"
    - app_kryta: "roles/app_kryta.md"
    - app_libreoffice: "roles/app_libreoffice.md"
    - app_msteams: "roles/app_msteams.md"
    - app_obs: "roles/app_obs.md"
    - app_pinta: "roles/app_pinta.md"
    - app_pitivi: "roles/app_pitivi.md"
    - app_shotcut: "roles/app_shotcut.md"
    - app_skype: "roles/app_skype.md"
    - app_slack: "roles/app_slack.md"
    - app_spotify: "roles/app_spotify.md"
    - app_tilix: "roles/app_tilix.md"
    - app_vscode: "roles/app_vscode.md"
    - app_xmind: "roles/app_xmind.md"
    - app_zoom: "roles/app_zoom.md"
    - auto_ansible_control: "roles/auto_ansible_control.md"
    - auto_ansible_node: "roles/auto_ansible_node.md"
    - auto_aplatform64: "roles/auto_aplatform64.md"
    - bkp_archive: "roles/bkp_archive.md"
    - bkp_rclone_server: "roles/bkp_rclone_server.md"
    - bkp_restic: "roles/bkp_restic.md"
    - cnt_docker: "roles/cnt_docker.md"
    - cnt_kubectl: "roles/cnt_kubectl.md"
    - cnt_podman: "roles/cnt_podman.md"
    - cloud_aws_cli: "roles/cloud_aws_cli.md"
    - cloud_azure_cli: "roles/cloud_azure_cli.md"
    - cloud_foundry_cli: "roles/cloud_foundry_cli.md"
    - cloud_google_cli: "roles/cloud_google_cli.md"
    - cloud_ibm_cli: "roles/cloud_ibm_cli.md"
    - db_mariadb_client: "roles/db_mariadb_client.md"
    - db_mariadb_server: "roles/db_mariadb_server.md"
    - db_mysql_client: "roles/db_mysql_client.md"
    - db_mysql_server: "roles/db_mysql_server.md"
    - db_postgresql_client: "roles/db_postgresql_client.md"
    - db_postgresql_server: "roles/db_postgresql_server.md"
    - dev_gcc: "roles/dev_gcc.md"
    - dev_java: "roles/dev_java.md"
    - dev_nodejs: "roles/dev_nodejs.md"
    - dev_opencl: "roles/dev_opencl.md"
    - dev_python: "roles/dev_python.md"
    - dev_ruby: "roles/dev_ruby.md"
    - dev_tools: "roles/dev_tools.md"
    - dops_ansiblelint: "roles/dops_ansiblelint.md"
    - dops_batscore: "roles/dops_batscore.md"
    - dops_git_client: "roles/dops_git_client.md"
    - dops_git_server: "roles/dops_git_server.md"
    - dops_github_cli: "roles/dops_github_cli.md"
    - dops_gitlab_server: "roles/dops_gitlab_server.md"
    - dops_jenkins: "roles/dops_jenkins.md"
    - dops_molecule: "roles/dops_molecule.md"
    - dops_shellcheck: "roles/dops_shellcheck.md"
    - dops_tfsec: "roles/dops_tfsec.md"
    - dops_yamllint: "roles/dops_yamllint.md"
    - hpv_libvirt_client: "roles/hpv_libvirt_client.md"
    - hpv_libvirt_server: "roles/hpv_libvirt_server.md"
    - hw_gpu_amd: "roles/hw_gpu_amd.md"
    - infra_helm: "roles/infra_helm.md"
    - infra_terraform: "roles/infra_terraform.md"
    - infra_terragrunt: "roles/infra_terragrunt.md"
    - infra_vagrant: "roles/infra_vagrant.md"
    - mon_fluentd: "roles/mon_fluentd.md"
    - net_bind: "roles/net_bind.md"
    - net_istioctl: "roles/net_istioctl.md"
    - sec_firewall_os: "roles/sec_firewall_os.md"
    - sec_firewall_os: "roles/sec_firewall_os.md"
    - sec_key_ssh: "roles/sec_key_ssh.md"
    - sec_openssh_client: "roles/sec_openssh_client.md"
    - sec_openssh_server: "roles/sec_openssh_server.md"
    - stg_autofs: "roles/stg_autofs.md"
    - stg_nfs_client: "roles/stg_nfs_client.md"
    - stg_nfs_server: "roles/stg_nfs_server.md"
    - stg_repository: "roles/stg_repository.md"
    - sys_dconf: "roles/sys_dconf.md"
    - sys_fonts: "roles/sys_fonts.md"
    - sys_gui_cinnamon: "roles/sys_gui_cinnamon.md"
    - sys_kernel: "roles/sys_kernel.md"
    - sys_mc: "roles/sys_mc.md"
    - sys_package: "roles/sys_package.md"
    - sys_repository: "roles/sys_repository.md"
    - sys_shell: "roles/sys_shell.md"
    - sys_subsystem: "roles/sys_subsystem.md"
    - sys_sudo: "roles/sys_sudo.md"
    - sys_tools: "roles/sys_tools.md"
    - sys_user: "roles/sys_user.md"
    - web_haproxy: "roles/web_haproxy.md"
    - web_httpd: "roles/web_httpd.md"
    - web_mkdocs: "roles/web_mkdocs.md"
    - web_nginx: "roles/web_nginx.md"
