---
namespace: "serdigital64"
name: "network"
version: "1.0.0"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating network tools provisioning."
license:
  - "GPL-3.0-or-later"
tags:
  - "network"
dependencies:
  serdigital64.core: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
