---
namespace: "serdigital64"
name: "cloud"
version: "1.0.3"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating cloud tools provisioning"
license:
  - "GPL-3.0-or-later"
tags:
  - "cloud"
dependencies:
  community.aws: "*"
  serdigital64.backup: "*"
  serdigital64.system: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
