---
# Template: 4.6.0
name: "Lint / TestManSH"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"

jobs:
  lint-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare environment"
        run: "./bin/dev-lib-base"

      - name: "Download tools"
        run: "./bin/dev-lib-testmansh"

      - name: "Build app"
        run: "./bin/dev-build-bash"

      - name: "Lint app"
        shell: 'script -q -e -c "bash {0}"' # Required to avoid no TTY error
        run: "./bin/dev-lint-testmansh"
...
