---
# Template: 4.3.1
name: "Lint / TestManSH"

env:
  DEV_CICD_DEBUG: ""

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"

jobs:
  lint-testmansh:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        target:
          - "RHEL"
          - "UBUNTU"
          - "DEBIAN"
          - "FEDORA"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare dev environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        run: "./bin/dev-build-bash"

      - name: "Lint app"
        shell: 'script -q -e -c "bash {0}"' # Required to avoid no TTY error
        run: './bin/dev-test-testmansh "$DEV_TEST_TESTMANSH_CONTAINER_${{matrix.target}}"'
...
