---
# Template: 3.0.0
name: "Test / Bash"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/cli/**"
      - "test/batscore/cli/**"

jobs:
  test-rhel:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        target:
          - "rhel"
          - "centos"
          - "ubuntu"
          - "debian"
          - "fedora"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build -i"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-bash ${{matrix.target}}"
...
